
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Sep 14 18:41:00 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 29;
  public static final int QUESTIONMARK = 26;
  public static final int LPAREN = 5;
  public static final int SEMI = 8;
  public static final int L = 35;
  public static final int MINUS = 16;
  public static final int G = 34;
  public static final int RPAREN = 6;
  public static final int AND = 30;
  public static final int OR = 31;
  public static final int COMMA = 17;
  public static final int INC = 12;
  public static final int DIV = 22;
  public static final int GEQ = 36;
  public static final int PLUS = 15;
  public static final int IF = 24;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int EQUAL = 14;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int COMA = 7;
  public static final int NUMBER = 39;
  public static final int MOD = 23;
  public static final int IDENT = 40;
  public static final int VOID = 11;
  public static final int NOTSAME = 33;
  public static final int COLON = 27;
  public static final int SAME = 32;
  public static final int LBRACE = 3;
  public static final int ELSE = 25;
  public static final int LSQUARE = 18;
  public static final int READ = 10;
  public static final int CHARCONST = 38;
  public static final int RSQUARE = 19;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 41;
  public static final int PROG = 2;
  public static final int LEQ = 37;
  public static final int DEC = 13;
  public static final int PRINT = 9;
}

